server:
  port: :9096

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/push
    username: robert-push
    password: robert

# Min/Max Push Notification Hours
robert.push.server:
  minPushHour: 8
  maxPushHour: 19

management:
  server.port: 8081
  endpoints:
    web:
      exposure:
        include: info,health,metrics,prometheus
