spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/push
    username: robert-push
    password: robert
  jdbc:
    template:
      fetch-size: 10000
  task:
    scheduling:
      shutdown:
        await-termination: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus

robert.push.server:
  ## Min/Max Push Notification Hours
  min-push-hour: 8
  max-push-hour: 20

  scheduler:
    delay-in-ms: 30000

  max-number-of-outstanding-notification: 10000
  max-notifications-per-second: 200

  apns:
    inactive-rejection-reason: BadDeviceToken,DeviceTokenNotForTopic
    auth-token-file: file:/srv/token.p8
    auth-key-id: key
    team-id: team
    topic: topic

    #path to the trusted certificate chain
    trusted-client-certificate-chain:
